[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by Wyatt'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
    footer = 'Gebaut mit Wyatt'
    alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
    languageTag = "nl-NL"
    titleAddition = "Modern documentatie-thema"
    description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn â€” standaard."
    titleHome = "Doks thema"
    footer = 'Mogelijk gemaakt door Wyatt</a>'
    alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'
